# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateFromIBBs <- function(precs, m, total_draws) {
    .Call('_conliga_simulateFromIBBs', PACKAGE = 'conliga', precs, m, total_draws)
}

getBBQuantiles <- function(q, counts, means, precision) {
    .Call('_conliga_getBBQuantiles', PACKAGE = 'conliga', q, counts, means, precision)
}

simStickyHMM <- function(chr_mat, total_draws, self_trans, real_num_states, means, precision, gamma_a = 1.5, gamma_scale = 1/1.5) {
    .Call('_conliga_simStickyHMM', PACKAGE = 'conliga', chr_mat, total_draws, self_trans, real_num_states, means, precision, gamma_a, gamma_scale)
}

simStickyHMMGivenStateCopyNum <- function(chr_mat, total_draws, self_trans, real_num_states, means, precision, RCNs) {
    .Call('_conliga_simStickyHMMGivenStateCopyNum', PACKAGE = 'conliga', chr_mat, total_draws, self_trans, real_num_states, means, precision, RCNs)
}

simCountsFromLociCopyNum <- function(lcns, chr_mat, means, precision, total_draws, trans_mat, init_dist, hs) {
    .Call('_conliga_simCountsFromLociCopyNum', PACKAGE = 'conliga', lcns, chr_mat, means, precision, total_draws, trans_mat, init_dist, hs)
}

inferBBParamsWithPriors <- function(counts, iterations, means_sigma, precision_sigma, mean_priors, precision_prior, run_ref) {
    invisible(.Call('_conliga_inferBBParamsWithPriors', PACKAGE = 'conliga', counts, iterations, means_sigma, precision_sigma, mean_priors, precision_prior, run_ref))
}

runStickyHMM <- function(counts, chr_mat, max_states, means, precision, iterations, jump_size_prob, gamma_a, gamma_scale, sample_ref, thin, norm_sigma_s, norm_sigma_l, precision_sigma_s, precision_sigma_l, hpp_g_a, hpp_g_b, hpp_ak_a, hpp_ak_b, hpp_r_c, hpp_r_d, precision_p_shape, precision_p_scale, gg, rr, apk, init_hidden_states, init_state_rcn) {
    invisible(.Call('_conliga_runStickyHMM', PACKAGE = 'conliga', counts, chr_mat, max_states, means, precision, iterations, jump_size_prob, gamma_a, gamma_scale, sample_ref, thin, norm_sigma_s, norm_sigma_l, precision_sigma_s, precision_sigma_l, hpp_g_a, hpp_g_b, hpp_ak_a, hpp_ak_b, hpp_r_c, hpp_r_d, precision_p_shape, precision_p_scale, gg, rr, apk, init_hidden_states, init_state_rcn))
}

get_state_permutations <- function(p_file, n_states_file, total_iterations, burn_in, thin, K_states, num_obs, map_num_state, stephens_max_iters) {
    .Call('_conliga_get_state_permutations', PACKAGE = 'conliga', p_file, n_states_file, total_iterations, burn_in, thin, K_states, num_obs, map_num_state, stephens_max_iters)
}

lociStateDiff <- function(m) {
    .Call('_conliga_lociStateDiff', PACKAGE = 'conliga', m)
}

